// export {default as BankStatements } from './homepage/index';
export {default as BankStatements } from './modules/BankStatements';
export {default as MoneyDeposit } from './modules/MoneyDeposit';
export {default as BillPayment } from './BillPayment';
export {default as LayoutComp } from './modules/LayoutComp';
export {default as SendMoney} from './modules/SendMoney';
export {default as WithdrawMoney }from './modules/WithdrawMoney';
export {default as Login} from './Login';
export {default as SignUp }from './SignUp';
export {default as HomePage }from './HomePage';
export {default as LandingPage } from './LandingPage';
