
export { default as ShowTracksInAlbums} from './albums/ShowTracksInAlbums';
export { default as GetSeveralAlbums}from './albums/GetSeveralAlbums';
export { default as SearchAlbums}  from './searchpage/SearchAlbums';
export { default as AlbumPage} from './albums/index';
export { default as TrackSongs} from './songs-genres/TrackSongs';
export { default as ShowDetails}  from './songs-genres/ShowDetails';
export { default as ShowSongs} from './songs-genres/ShowSongs';
export { default as SongListsComp} from './songs-genres/index';
export { default as SearchArtistComp}  from '../components/search/SearchArtistComp';
export { default as SearchArtistsPage}  from './searchpage/SearchArtists';
export { default as JobAdverts} from './adverts/GitHubJobsComponent';
export { default as TopArtists} from './top-artists/index';
export { default as TopMusicComp} from './topmusic/index';
export { default as ArtistPage}from './artist/index';
export { default as MenuPage} from './menu/index';
export { default as DashboardComp} from './dashboard/index';
export { default as GenresComponent} from './genres/GenresComponent';
// export { default as ShowTracksInAlbums} from './genres/GenresComponent';
export { default as SignUpComp} from './auth/signup/index';
export { default as SignInComp} from './auth/signin/index';
